### ISSUE TITLE
Ошибка OpenGL

### ISSUE THREAD

**Issue by GreenMine** [night-glider/freerun-shooter#1]
Появилась следующая проблема. На компьютерах ЛГТУ(!) не работает данная великолепная игра. Как играть на парах?
![image (1)](https://user-images.githubusercontent.com/19375914/169799284-571347db-4d8e-434c-a392-0573b9fb8e7b.png)

**Comment by night-glider** [comment]
Спасибо за обращение! Да, я уже пытался запускать игру на политеховских компах. В 90% случаев получал именно эту ошибку. Это связано с тем, что игра работает на GLES3, а компьютер его не поддерживает. Это уже не проблема игры, а проблема устаревших видеокарт/драйверов компа.

Единственное, что я могу сделать - это перенести игру на GLES2. Это достаточно сильно затронуло графику, но это хоть что-то.

Пожалуйста, попробуй запустить этот билд в лгту и отпиши получилось ли
[bean_duel.zip](https://github.com/night-glider/freerun-shooter/files/8754625/bean_duel.zip)

**Comment by GreenMine** [comment]
А нельзя ли подгружать разные графические библиотеки? Например, если opengl не может загрузится, он gles2 будет подгружать

**Comment by night-glider** [comment]
Насколько я знаю, в рантайме нельзя. Хотя у движка открытый исходный код, так что...
